// Detail copy and existing campaign imagery for each service.
export const serviceDetails = {
  branding: [
    ['Logo Usage Guide', '品牌标识使用规范', 'Give your logo a consistent presence across every touchpoint. Usage guidelines explain clear space, minimum size, approved variations and placement on light or dark backgrounds.', ['Clear space and sizing', 'Primary, secondary and monochrome versions', 'Correct and incorrect usage'], 'business-card'],
    ['Brand Color Palette', '品牌标准色', 'Build a recognizable palette with primary and supporting colours. Colour specifications help keep printed materials and digital applications connected.', ['Primary and supporting colours', 'RGB and HEX for digital use', 'CMYK references for print'], 'posting-02'],
    ['Typography Selection', '品牌字体选择', 'Choose typefaces that express your brand and stay readable. A clear hierarchy guides headlines, body copy and small supporting text.', ['Headline and body font pairings', 'Weight, spacing and hierarchy', 'Font licensing and usage guidance'], 'poster'],
    ['Brand Applications', '品牌应用设计', 'See how your identity works beyond the logo. Selected applications connect everyday materials to one coherent visual direction.', ['Business cards and stationery', 'Uniforms and merchandise', 'Digital and social templates'], 'uniform'],
    ['High Resolution Files', '完整品牌标识设计档案', 'Receive organized artwork for the agreed brand identity scope, with formats suited to editing, printing and digital use.', ['Editable AI artwork where included', 'Transparent PNG and high-resolution JPG', 'Organized colour and logo variations'], 'business-card'],
    ['Brand Visual Identity', '品牌视觉识别', 'Bring logo, colour, type and supporting graphics together into an identity system. Each element helps your brand feel recognizable across different formats.', ['Graphic elements and patterns', 'Image and art direction', 'A connected identity system'], 'cover'],
    ['Layout & Composition Style', '排版风格设计', 'Define how the brand arranges information. Consistent grids, spacing and image treatments make new materials easier to create and recognize.', ['Layout grids and spacing', 'Text and image relationships', 'Examples across print and digital'], 'posting-02'],
  ],
  uniform: [
    ['Fabric & Material Direction', '布料与材质选择', 'Start with how the garment will be worn. We discuss cotton, cotton blends, polyester performance fabrics and piqué options against comfort, breathability, care and budget needs.', ['Cotton and blended fabrics', 'Performance polyester and piqué options', 'Fabric weight, feel and colour samples'], 'uniform'],
    ['Fit, Cut & Garment Details', '版型与服装细节', 'Choose a silhouette suited to your team and working environment. Collar, sleeve, pocket and fastening details can make a uniform both useful and distinctive.', ['T-shirts, polos and workwear direction', 'Size range and fit references', 'Collars, cuffs, pockets and trims'], 'uniform'],
    ['Printing Techniques', '印刷工艺', 'Compare screen printing, heat transfer, DTF and sublimation for your artwork and garment. The appropriate method depends on fabric, colour, quantity and the desired finish.', ['Screen printing for suitable repeat artwork', 'Heat transfer and DTF for detailed graphics', 'Sublimation for compatible polyester garments'], 'posting-02'],
    ['Embroidery & Finishing', '刺绣与加工工艺', 'Explore stitched branding and finishing details that complement the garment. Final technique choices are reviewed against artwork complexity and material suitability.', ['Embroidery size and stitch direction', 'Woven labels, patches and branded trims', 'Seam, hem and placement details'], 'uniform'],
    ['Artwork, Sampling & Production', '设计确认与生产协调', 'Bring the design into a clear production brief. Size specifications, artwork placement and samples help align expectations before the agreed production run.', ['Artwork dimensions and placement sheets', 'Sample review and size confirmation', 'Production scope, quantity and finishing checks'], 'business-card'],
  ],
  graphic: [
    ['Creative Direction & Key Visuals', '创意方向与主视觉', 'Turn a message into a clear visual concept. Typography, colour and imagery work together to set the tone of a campaign or communication.', ['Concept and visual references', 'Key visual and graphic elements', 'Consistent brand application'], 'cover'],
    ['Print & Marketing Collateral', '印刷与宣传物料', 'Design materials people can read, use and remember. Each format balances information hierarchy with the practical needs of printing.', ['Posters, flyers and brochures', 'Business cards and stationery', 'Bleed, trim and print preparation'], 'poster'],
    ['Packaging & Layout', '包装与版面设计', 'Build layouts around the product and the information customers need. Packaging artwork follows the supplied structural specifications and agreed production requirements.', ['Packaging graphics and label design', 'Layout, hierarchy and content placement', 'Artwork aligned to supplied dielines'], 'business-card'],
    ['Digital Assets & Handover', '数码素材与文件交付', 'Adapt the design for the channels where your audience sees it. Deliverables and editable formats are agreed around your team’s needs.', ['Social posts and digital banners', 'Channel-specific sizes and variations', 'Export files and agreed templates'], 'posting-02'],
  ],
  merchandise: [
    ['Product Selection & Curation', '产品选择与企划', 'Choose goods that fit your audience, occasion and budget. A considered selection helps a branded item feel useful rather than disposable.', ['Event gifts and team essentials', 'Apparel, bags and everyday accessories', 'Quantity, use case and budget direction'], 'posting-03'],
    ['Materials & Brand Placement', '材质与品牌应用', 'Match your identity to the product’s shape, material and printable area. Scale and placement keep the branding clear without overwhelming the item.', ['Material and colour direction', 'Logo scale and artwork placement', 'Coordinated product mockups'], 'uniform'],
    ['Decoration & Production Details', '定制工艺与生产细节', 'Discuss printing, embroidery, engraving or other decoration options according to the selected product. Samples and supplier specifications guide the final approach.', ['Surface and artwork suitability', 'Decoration method and finish options', 'Sample and production specification review'], 'posting-03'],
    ['Packaging & Collection Design', '包装与系列搭配', 'Bring individual pieces together into a coherent collection. Packaging and supporting print materials complete the gifting or event experience.', ['Gift sets and collection styling', 'Packaging graphics and inserts', 'Coordinated colour and visual language'], 'business-card'],
  ],
  'photo-videography': [
    ['Creative Direction & Shoot Planning', '创意方向与拍摄规划', 'Define the story before the shoot. References, a shot list and a practical schedule help connect the visuals to your brand and intended channels.', ['Moodboards and visual references', 'Shot list and storyboard direction', 'Location, styling and schedule planning'], 'cover'],
    ['Brand & Product Photography', '品牌与产品摄影', 'Plan imagery around the qualities you want people to notice. Composition, background and lighting direction help build a consistent image library.', ['Product and detail compositions', 'Brand, team and lifestyle direction', 'Lighting and background consistency'], 'posting-03'],
    ['Video & Short-form Content', '影片与短视频内容', 'Shape a clear narrative for campaigns, products or social content. Duration, framing and the final channel guide the filming and editing approach.', ['Campaign and product storytelling', 'Vertical and horizontal formats', 'Sequences, pacing and on-screen text'], 'poster'],
    ['Editing & Delivery', '后期处理与素材交付', 'Bring the selected material into one visual direction. Editing and export specifications are aligned with the agreed deliverables.', ['Image selection and colour treatment', 'Video editing and agreed audio approach', 'Resolution, aspect ratio and export formats'], 'posting-02'],
  ],
  'marketing-services': [
    ['Campaign Direction & Messaging', '营销方向与信息规划', 'Start with the audience, objective and message. A focused creative direction helps the campaign communicate clearly across its chosen channels.', ['Audience and communication goals', 'Campaign concept and key messages', 'Visual direction and content themes'], 'cover'],
    ['Social & Digital Campaign Assets', '社交媒体与数码营销素材', 'Create a connected set of materials for your campaign. Format variations help the same idea work across posts, stories and digital placements.', ['Social posts, stories and banners', 'Copy and design coordination', 'Channel-specific artwork sizes'], 'posting-02'],
    ['Launch & Promotional Materials', '发布与推广物料', 'Coordinate the pieces a launch or promotion needs. Digital and physical materials can share the same headline, imagery and visual language.', ['Launch key visuals and announcements', 'Promotional print and digital assets', 'Coordinated event or campaign materials'], 'poster'],
    ['Content Planning & Consistency', '内容规划与品牌一致性', 'Give your team a clearer framework for keeping the brand visible. Content themes and agreed templates support a consistent presence over time.', ['Content themes and publishing plan', 'Reusable design templates', 'Review and refinement of creative materials'], 'business-card'],
  ],
};
