"""Generate uncropped, responsive WebP assets with Pillow (no runtime dependency).

Run: python scripts/optimize-images.py
Requires Pillow with WebP support. Original files remain untouched.
"""
import hashlib
import json
from pathlib import Path

from PIL import Image, ImageOps, features

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / "public"
assert features.check("webp"), "Pillow needs WebP support"

sources = sorted((PUBLIC / "visuals").glob("*.jpg"))
sources += sorted((PUBLIC / "client-logos").glob("*.png"))
sources += [PUBLIC / "abound-logo.png"]
manifest = {}
for source in sources:
    relative = source.relative_to(PUBLIC)
    key = "/" + relative.as_posix()
    with Image.open(source) as original:
        image = ImageOps.exif_transpose(original)
        width, height = image.size
        transparent = image.mode == "RGBA"
        image = image.convert("RGBA" if transparent else "RGB")
        requested = [180, 360, 540] if "client-logos" in key else (
            [144, 288, 576, 960] if source.name == "abound-logo.png" else
            [480, 768, 1200, 1600, 2400, 3200]
        )
        widths = sorted({min(size, width) for size in requested})
        folder = PUBLIC / "optimized" / relative.parent
        folder.mkdir(parents=True, exist_ok=True)
        variants = []
        for target_width in widths:
            target_height = max(1, round(height * target_width / width))
            resized = image.resize((target_width, target_height), Image.Resampling.LANCZOS)
            target = folder / f"{source.stem}-{target_width}.webp"
            # Lossless transparent logos preserve clean edges and alpha channels.
            resized.save(target, "WEBP", quality=92, method=6, lossless=transparent,
                         exact=transparent, icc_profile=original.info.get("icc_profile", b""))
            with Image.open(target) as check:
                assert check.size == (target_width, target_height)
                assert check.mode == image.mode
            variants.append({"src": "/" + target.relative_to(PUBLIC).as_posix(),
                             "width": target_width, "height": target_height,
                             "bytes": target.stat().st_size})
        default = min(variants, key=lambda variant: abs(variant["width"] - (360 if transparent else 1200)))
        entry = {"width": width, "height": height, "originalBytes": source.stat().st_size,
                 "originalSha256": hashlib.sha256(source.read_bytes()).hexdigest(),
                 "variants": variants, "default": default["src"]}
        if not transparent:
            # Sharing crawlers receive a smaller JPEG, with the same aspect ratio.
            share_width = min(1200, width)
            share = folder / f"{source.stem}-share.jpg"
            image.resize((share_width, round(height * share_width / width)), Image.Resampling.LANCZOS).save(
                share, "JPEG", quality=92, subsampling=0, optimize=True,
                icc_profile=original.info.get("icc_profile", b""))
            entry["share"] = "/" + share.relative_to(PUBLIC).as_posix()
            entry["shareBytes"] = share.stat().st_size
        manifest[key] = entry
        print(f"{relative}: {source.stat().st_size:,} -> {next(v['bytes'] for v in variants if v['src'] == default['src']):,} bytes (default WebP)", flush=True)

runtime_manifest = {
    key: {"width": item["width"], "height": item["height"], "default": item["default"],
          "variants": [{"src": variant["src"], "width": variant["width"]} for variant in item["variants"]],
          **({"share": item["share"]} if "share" in item else {})}
    for key, item in manifest.items()
}
(ROOT / "image-manifest.js").write_text(
    "// Generated by scripts/optimize-images.py; do not edit by hand.\nexport const imageManifest = "
    + json.dumps(runtime_manifest, indent=2) + ";\n", encoding="utf-8")
(ROOT / "image-sizes.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
print(f"Generated responsive variants for {len(manifest)} original images.")
